CREATE TABLE IF NOT EXISTS parsed(
	`id`	INTEGER	PRIMARY KEY	NOT NULL,
	`date`  DATE
);

CREATE TABLE IF NOT EXISTS logs(
	`id`	INTEGER	PRIMARY KEY	NOT NULL,
	`datetime`  DATETIME,
	`type`	VARCHAR	NOT NULL,
	`message`	TEXT
);

CREATE TABLE IF NOT EXISTS data(
	`id`	INTEGER	PRIMARY KEY	NOT NULL,
	`datetime`  DATETIME,
	`ms`	INTEGER NOT NULL,
	`type`	VARCHAR	NOT NULL,
	`name`	VARCHAR	NOT NULL,
	`data`	TEXT
);